services:
  orthanc:
    image: orthancteam/orthanc:25.8.2
    container_name: orthanc
    ports:
      - "${ORTHANC_HTTP_PORT:-8042}:8042"
      - "${ORTHANC_DICOM_PORT:-4242}:4242"
    volumes:
      - ./pacs-data/orthanc-db:/var/lib/orthanc/db
    environment:
      ORTHANC__NAME: Orthanc
      ORTHANC__REMOTE_ACCESS_ALLOWED: "true"
      ORTHANC__DICOM_WEB__ENABLE: "true"
      ORTHANC__DICOM_WEB__ROOT: "/dicom-web"
    networks:
      - dicom_net
    restart: unless-stopped

  ohif:
    image: ohif/viewer:latest
    container_name: ohif-viewer
    ports:
      - "${OHIF_PORT:-3001}:80"
    volumes:
      - ./ohif-config/app-config.js:/usr/share/nginx/html/app-config.js:ro
      - ./ohif-config/config/default.js:/usr/share/nginx/html/config/default.js:ro
      - ./ohif-config/manifest.json:/usr/share/nginx/html/manifest.json:ro
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - dicom_net
    depends_on:
      - orthanc
    restart: unless-stopped

  dicom-sender:
    build: ./dicom-sender
    container_name: dicom-sender
    environment:
      - PACS_HOSTNAME=${PACS_HOSTNAME:-orthanc}
      - PACS_AETITLE=${PACS_AETITLE:-ORTHANC}
      - PACS_PORT=${PACS_PORT:-4242}
      - SENDER_AETITLE=${SENDER_AETITLE:-CT_SCANNER}
    volumes:
      - ./dicom-sender/sample-dicoms:/dicoms
    networks:
      - dicom_net
    depends_on:
      - orthanc
    command: sh -c "echo 'Attente de 25s pour le démarrage stable du PACS...' && sleep 25 && python send_dicoms.py"
    restart: unless-stopped

networks:
  dicom_net:
    driver: bridge
